### ISSUE TITLE
Why not run in production?

### ISSUE THREAD

**Issue by GeoffreyPlitt** [withspectrum/rethinkdb-inspector#12]
It's mentioned not to run this in production. Why not?

**Comment by mxstbr** [comment]
It uses a lot of memory and will most likely make all of your queries run a couple percentage points slower. If you're okay with that feel free to run it in prod, but at your own risk!

**Comment by GeoffreyPlitt** [comment]
One last follow-up question: Does this use a lot of memory on the *database* nodes, or just in the NodeJS box where it runs? The former is a big problem for us, but the latter is no prob at all, we can just spin up an isolated box.

**Comment by mxstbr** [comment]
The latter!

**Comment by GeoffreyPlitt** [comment]
thanks!

**Comment by GeoffreyPlitt** [comment]
@mxstbr 

Follow-up question: I'm perusing the code, and I don't see any reasons at first glance, that there would be increased memory usage. Why do you think that's the case.

Also re: time. It doesn't seem like it would slow queries down by a multiplier, as you indicated, but more as an addition. So longest queries wouldn't be much different. Am I misunderstanding the code?
